# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('score', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='SideA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SideB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='ablink',
            name='side_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugdemo.SideA'),
        ),
        migrations.AddField(
            model_name='ablink',
            name='side_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugdemo.SideB'),
        ),
        migrations.AlterUniqueTogether(
            name='ablink',
            unique_together=set([('side_a', 'side_b'), ('side_a', 'ranking', 'side_b')]),
        ),
        migrations.AlterIndexTogether(
            name='ablink',
            index_together=set([('side_a', 'ranking', 'side_b')]),
        ),
    ]
